### ISSUE TITLE
第一个模块，注册和登陆

### ISSUE THREAD

**Issue by gigantic2** [presentianz/b2c#3]
惯例，写代码之前，先pull一下。
### FosuserBundle

项目里我们直接使用[FosuserBundle](https://github.com/FriendsOfSymfony/FOSUserBundle)，之后还需要支持微信，微博和qq的第三方登陆，那个之后在搞。

用来发系统邮件的邮箱密码 (support@presentia.co.nz) 我会发到微信群里，或者测试也可以用你自己的邮箱在本地测试。

你需要在controller user和admin分别写一个测试路由，只允许登陆后访问，权限分别为user和admin role。先按照fosuserbundle文档，研究下怎么改写模板和控制器，有什么问题找我即可。

以上是LJQ下一步要做的工作。
### 数据库设计和mapping

所有的Entitiy和之间关系由我来写。
### 路由设计

HZ你可以尝试下网站路由设计的工作么？比如我们需要哪些页面，他们的路由分别是什么，总结一下，有问题直接问我。比如当前创建这个issue的路由就是main_url/presentianz/b2c/issues/new。

**Comment by ZoeyeoZ** [comment]
好的👌

**Comment by liujiaqi** [comment]
ok

**Comment by ZoeyeoZ** [comment]
这是我目前的想法。

page
主页：URL
联系方式：
    URL/service/contact
帮助中心：
    URL/service/cus
    URL/service/seller
注册：URL/account/reg.html
登录：URL/account/login.html

product
产品类别：URL/market/分类名/list
产品搜索：URL/market/search?q=
商店展示：
    URL/shop/view_shop  &sid=
商店产品：
    URL/shop/item   &pid=
商店目录：
    URL/shop/category

cart
购物车：URL/account/cart
生成订单：URL/account/order_new
收藏夹：URL/account/collect

account
账户主页：
    URL/account/home
设置：
    收货地址：
    URL/account/setting/deliver_address
    个人信息：
    URL/account/setting/account_security
订单列表：
    URL/account/order_list
消息：URL/account/msg

admin
URL/admin/home
上架：URL/admin/publish_new
查看：URL/admin/publish_inf
修改：URL/admin/publish_rev
在出售货品：URL/admin/list_sell_items
已卖出货品：URL/admin/list_sold_items
查看用户：URL/admin/list_cus
物流：
    URL/admin/post
    等待发货：URL/admin/list_older_new
    发货中：URL/admin/list_older_confirm
    已发货：URL/admin/list_older_finish
售后：URL/admin/seller_admin
评价：URL/admin/rate_admin

**Comment by presentianz** [comment]
Nicely done.
